#!/usr/bin/env python3
"""Regenerate docs/functions.md from function_descriptions.csv.

Run with:  uv run tools/gen_functions_doc.py

docs/functions.md is generated, never hand-edited (AGENTS.md workflow rule:
"New or changed function -> update function_descriptions.csv, ... regenerate
docs/functions.md").
"""

import csv
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "function_descriptions.csv"
OUT_PATH = ROOT / "docs" / "functions.md"

GROUP_TITLES = {
    "pixel": "Pixel functions",
    "moc": "MOC type and functions",
    "sky": "Sky predicates",
    "macro": "SQL macros",
}


def main() -> None:
    with CSV_PATH.open(newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))

    missing = [r["function"] for r in rows if not r["description"] or not r["example"]]
    if missing:
        raise SystemExit(
            f"function_descriptions.csv: missing description or example for {missing}"
        )

    lines = [
        "<!-- Generated by tools/gen_functions_doc.py from function_descriptions.csv.",
        "     Do not edit by hand. -->",
        "",
        "# duckdb-healpix function reference",
        "",
        f"{len(rows)} function(s). All angles are degrees, ICRS, `DOUBLE`.",
        "All pixel indices are NESTED, `BIGINT`. Order is `INT` in `[0, 29]`.",
        "",
    ]

    for group in dict.fromkeys(r["group"] for r in rows):
        lines += [f"## {GROUP_TITLES.get(group, group)}", ""]
        for row in (r for r in rows if r["group"] == group):
            lines += [
                f"### `{row['function']}`",
                "",
                f"```sql",
                f"{row['signature']} -> {row['returns']}",
                "```",
                "",
                row["description"],
                "",
                "```sql",
                row["example"],
                "```",
                "",
            ]

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(ROOT)} ({len(rows)} function(s))")


if __name__ == "__main__":
    main()
